### ISSUE TITLE
SPEED ISSUE

### ISSUE THREAD

**Issue by susantha1995** [TheYellowArchitect/YoutubeDL-PowerGUI#17]
Hi, download is very low like 2G. I'm using this script on VPS server high-speed connection. but video download only in KBS and very low.  how to fix this please??

**Comment by TheYellowArchitect** [comment]
Your setup is probably to blame, or the website which you download throttles/bottlenecks your download speed
This had happened in the past, where [youtube-dl](https://github.com/ytdl-org/youtube-dl) was throttled by Youtube.

This PowerGUI as the title says, runs [youtube-dlp](https://github.com/yt-dlp/yt-dlp), so if you have speed issues, open an issue there

Anyway, as I said at the start, its probably the website or your VPS has download restrictions. Try using this on your personal computer and tell me how many MB/s it downloads, so as to confirm there is a download speed issue or just your setup
